<a href="https://colab.research.google.com/github/geethanjalins/luxuryhouseInBangalore/blob/main/LuxuryhouseSale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Uploading

In [ ]:
import pandas as pd
import math
luxuryhouse_df = pd.read_csv('/content/Luxury_Housing_Bangalore.csv')
luxuryhouse_df.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

# renaming the column

In [ ]:
luxuryhouse_df = luxuryhouse_df.rename(columns={'Micro_Market':'Area','Configuration':'Bedrooms'})
luxuryhouse_df['Ticket_Price_Cr'] = pd.to_numeric(luxuryhouse_df['Ticket_Price_Cr'], errors='coerce')
luxuryhouse_df.head()

,Property_ID,Area,Project_Name,Developer_Name,Unit_Size_Sqft,Bedrooms,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

# Drop Duplicates

In [ ]:
luxuryhouse_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Area                  101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Bedrooms              101000 non-null  object
 6   Ticket_Price_Cr       72770 non-null   float64
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(5), int64(1), object(12)
memory usage: 13.9+ MB

In [ ]:
luxuryhouse_df['Property_ID'] = luxuryhouse_df['Property_ID'].astype(str).str.replace(r'\D', '', regex=True)
luxuryhouse_df['Project_Name'] = luxuryhouse_df['Project_Name'].astype(str).str.replace(r'\D', '', regex=True)
luxuryhouse_df['Bedrooms'] = luxuryhouse_df['Bedrooms'].astype(str).str.replace(r'\D', '', regex=True)

luxuryhouse_df.tail()

,Property_ID,Area,Project_Name,Developer_Name,Unit_Size_Sqft,Bedrooms,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
100995,004730,BELLARY ROAD,229,Embassy,8546.0,5,11.330810,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,059810,Bellary Road,309,Brigade,3408.0,3,10.829373,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,065099,HENNUR ROAD,98,RMZ,4691.0,4,11.183303,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,093022,rajajinagar,21,Embassy,7435.0,3,10.914156,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,023826,whitefield,325,L&T Realty,3218.0,4,NaN,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [ ]:
luxuryhouse_df['Bedrooms'] = pd.to_numeric(luxuryhouse_df['Bedrooms'],errors='coerce')
luxuryhouse_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Area                  101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Bedrooms              101000 non-null  int64
 6   Ticket_Price_Cr       72770 non-null   float64
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(5), int64(2), object(11)
memory usage: 13.9+ MB

# Duplicates

In [ ]:
luxuryhouse_df[luxuryhouse_df.duplicated].reset_index(drop=True)
luxuryhouse_df.drop_duplicates(inplace=True)
luxuryhouse_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Area                  100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        90043 non-null   float64
 5   Bedrooms              100000 non-null  int64
 6   Ticket_Price_Cr       72049 non-null   float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
dtypes: float64(5), int64(2), object(11)
memory usage: 14.5+ MB

# Null Values

In [ ]:
all_nan_columns = luxuryhouse_df.columns[luxuryhouse_df.isnull().any()]
print(all_nan_columns)

Index(['Unit_Size_Sqft', 'Ticket_Price_Cr', 'Amenity_Score', 'Buyer_Comments'], dtype='object')

In [ ]:
luxuryhouse_df.isnull().sum()

Property_ID                 0
Area                        0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft           9957
Bedrooms                    0
Ticket_Price_Cr         27951
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10000
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18099
dtype: int64

In [ ]:
luxuryhouse_df['Bedrooms'].unique()

array([4, 3, 5])

In [ ]:
luxuryhouse_df['Developer_Name'].unique()

array(['RMZ', 'Puravankara', 'Tata Housing', 'Embassy', 'SNN Raj',
       'Brigade', 'Prestige', 'Total Environment', 'Godrej', 'L&T Realty',
       'Sobha'], dtype=object)

In [ ]:
luxuryhouse_df['Bedrooms'].value_counts()

Bedrooms
5    33536
3    33377
4    33087
Name: count, dtype: int64

In [ ]:
luxuryhouse_df[['Developer_Name','Bedrooms','Unit_Size_Sqft']]

      Developer_Name  Bedrooms  Unit_Size_Sqft
0                RMZ         4          4025.0
1        Puravankara         3          5760.0
2       Tata Housing         4          7707.0
3            Embassy         3          6192.0
4            SNN Raj         4          7147.0
...              ...       ...             ...
99995     L&T Realty         5          5550.0
99996     L&T Realty         4          3171.0
99997       Prestige         4          5599.0
99998        SNN Raj         4          7342.0
99999        Embassy         5          5016.0

[100000 rows x 3 columns]

In [ ]:

luxuryhouse_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Area                  100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        90043 non-null   float64
 5   Bedrooms              100000 non-null  int64
 6   Ticket_Price_Cr       72049 non-null   float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
dtypes: float64(5), int64(2), object(11)
memory usage: 14.5+ MB

In [ ]:
mean_value = luxuryhouse_df.groupby('Unit_Size_Sqft').Bedrooms.mean()

In [ ]:
luxuryhouse_df['Unit_Size_Sqft'] = luxuryhouse_df['Unit_Size_Sqft'].fillna(mean_value)

In [ ]:
luxuryhouse_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Area                  100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        90643 non-null   float64
 5   Bedrooms              100000 non-null  int64
 6   Ticket_Price_Cr       72049 non-null   float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
dtypes: float64(5), int64(2), object(11)
memory usage: 14.5+ MB

In [ ]:
luxuryhouse_df.isnull().sum()

Property_ID                 0
Area                        0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft           9357
Bedrooms                    0
Ticket_Price_Cr         27951
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10000
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18099
dtype: int64

In [ ]:
print('unique values in Unit_Size_Sqft',luxuryhouse_df['Bedrooms'].unique())

unique values in Unit_Size_Sqft [4 3 5]

In [ ]:
luxuryhouse_df.isnull().sum()

Property_ID                 0
Area                        0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft           9357
Bedrooms                    0
Ticket_Price_Cr         27951
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10000
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18099
dtype: int64

In [ ]:
luxuryhouse_df[luxuryhouse_df['Unit_Size_Sqft'].isnull()]

,Property_ID,Area,Project_Name,Developer_Name,Unit_Size_Sqft,Bedrooms,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
17,000018,YELAHANKA,17,L&T Realty,NaN,4,9.045290,Secondary,CXO,2024-03-31,8.793448,5.186328,Ready to move,NRI Desk,yes,9.256085,77,Loved the amenities!
18,000019,YELAHANKA,18,Total Environment,NaN,5,7.623657,Primary,Other,2024-12-31,6.111031,6.898634,Ready to move,Broker,yes,8.652232,118,Connectivity is poor.
24,000025,Mg Road,24,L&T Realty,NaN,3,NaN,Primary,Other,2024-03-31,9.300782,9.464122,Under construction,Online,no,8.127972,43,Agent was not responsive.
33,000034,jp nagar,33,Tata Housing,NaN,5,15.018780,Primary,CXO,2024-09-30,7.991544,5.489478,Ready to move,Direct,yes,6.337526,64,Great value for money.
45,000046,Mg Road,45,Brigade,NaN,5,15.671783,Primary,NRI,2023-12-31,8.186105,9.515085,Launch,NRI Desk,yes,5.414198,57,Agent was not responsive.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99942,099943,Bellary Road,442,SNN Raj,NaN,3,13.870145,Secondary,Other,2025-03-31,6.407603,7.377709,Launch,Broker,no,5.639231,41,Connectivity is poor.
99951,099952,Whitefield,451,Prestige,NaN,3,11.783487,Secondary,HNI,2024-03-31,7.262669,5.038248,Ready to move,Broker,yes,8.992345,115,NaN
99957,099958,SARJAPUR ROAD,457,Sobha,NaN,5,10.431024,Primary,NRI,2024-03-31,4.369459,6.544910,Ready to move,Direct,no,8.868635,61,Great view from 15th floor.
99972,099973,BANNERGHATTA ROAD,472,SNN Raj,NaN,5,11.512373,Primary,NRI,2023-06-30,4.857654,6.766822,Ready to move,Broker,no,8.563902,19,Too far from my office.
99976,099977,HENNUR ROAD,476,Brigade,NaN,4,9.011187,Secondary,Startup Founder,2023-12-31,5.493179,5.909716,Ready to move,NRI Desk,no,9.005722,83,Connectivity is poor.

In [ ]:
luxuryhouse_df['Bedrooms'] = luxuryhouse_df['Bedrooms'].astype(int)

In [ ]:
mean_bedrooms = luxuryhouse_df['Bedrooms'].mean()


luxuryhouse_df['Unit_Size_Sqft'] = luxuryhouse_df['Unit_Size_Sqft'].fillna(mean_bedrooms)

In [ ]:
luxuryhouse_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Area                  100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Bedrooms              100000 non-null  int64
 6   Ticket_Price_Cr       72049 non-null   float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         90000 non-null   float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
dtypes: float64(5), int64(2), object(11)
memory usage: 14.5+ MB

In [ ]:
import numpy as np

In [ ]:
luxuryhouse_df['Ticket_Price_Cr'] = np.where(luxuryhouse_df['Ticket_Price_Cr'].isnull(),luxuryhouse_df['Ticket_Price_Cr'].mode(),luxuryhouse_df['Ticket_Price_Cr'])

In [ ]:
luxuryhouse_df.isnull().sum()

Property_ID                 0
Area                        0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Bedrooms                    0
Ticket_Price_Cr             0
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10000
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18099
dtype: int64

In [ ]:
import numpy as np

# Calculate the mode of the 'Amenity_Score' column
mode_value = luxuryhouse_df['Amenity_Score'].mode()[0]

# Fill nulls with the mode
luxuryhouse_df['Amenity_Score'] = luxuryhouse_df['Amenity_Score'].fillna(mode_value)

In [ ]:
luxuryhouse_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Area                  100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Bedrooms              100000 non-null  int64
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
dtypes: float64(5), int64(2), object(11)
memory usage: 14.5+ MB

In [ ]:
luxuryhouse_df

,Property_ID,Area,Project_Name,Developer_Name,Unit_Size_Sqft,Bedrooms,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,000001,Sarjapur Road,0,RMZ,4025.0,4,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,000002,Indiranagar,1,Puravankara,5760.0,3,16.292152,Primary,Other,2024-06-30,4.839024,5.000224,Under construction,NRI Desk,no,7.723898,106,NaN
2,000003,Bannerghatta Road,2,Tata Housing,7707.0,4,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,000004,bellary road,3,Embassy,6192.0,3,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,000005,Koramangala,4,SNN Raj,7147.0,4,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,099996,bellary road,495,L&T Realty,5550.0,5,10.185193,Primary,NRI,2023-12-31,8.379908,5.000224,Under construction,Online,yes,8.378800,109,Underpriced for location.
99996,099997,YELAHANKA,496,L&T Realty,3171.0,4,12.272081,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.
99997,099998,rajajinagar,497,Prestige,5599.0,4,13.730179,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,NRI Desk,yes,8.984990,63,NaN
99998,099999,INDIRANAGAR,498,SNN Raj,7342.0,4,10.363989,Primary,NRI,2024-09-30,9.435646,6.369276,Under construction,NRI Desk,yes,7.634717,89,NaN
99999,100000,hennur road,499,Embassy,5016.0,5,10.415617,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,yes,6.039943,95,NaN

In [ ]:
luxuryhouse_df.to_csv('luxuryhouse_data.csv', index=False)

In [ ]:
luxuryhouse_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Area                  100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Bedrooms              100000 non-null  int64
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        81901 non-null   object
dtypes: float64(5), int64(2), object(11)
memory usage: 16.5+ MB

In [ ]:
import pandas as pd
import math
luxuryhouse_df = pd.read_csv('/content/luxuryhouse_data.csv')
luxuryhouse_df.head()

,Property_ID,Area,Project_Name,Developer_Name,Unit_Size_Sqft,Bedrooms,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,1,Sarjapur Road,0,RMZ,4025.0,4,12.750846,Primary,NRI,3/31/2025,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,2,Indiranagar,1,Puravankara,5760.0,3,16.292152,Primary,Other,6/30/2024,4.839024,5.000224,Under construction,NRI Desk,no,7.723898,106,NaN
2,3,Bannerghatta Road,2,Tata Housing,7707.0,4,10.517724,Primary,HNI,12/31/2023,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,4,bellary road,3,Embassy,6192.0,3,9.396367,Primary,HNI,3/31/2024,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,5,Koramangala,4,SNN Raj,7147.0,4,15.345392,Secondary,HNI,12/31/2024,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [ ]:
area_name = luxuryhouse_df['Area'].unique()
print(area_name)

['Sarjapur Road' 'Indiranagar' 'Bannerghatta Road' 'bellary road'
 'Koramangala' 'YELAHANKA' 'whitefield' 'sarjapur road' 'JP NAGAR'
 'Rajajinagar' 'koramangala' 'WHITEFIELD' 'indiranagar' 'jayanagar'
 'Whitefield' 'DOMLUR' 'yelahanka' 'Mg Road' 'HENNUR ROAD' 'Jayanagar'
 'Domlur' 'Electronic City' 'Hebbal' 'mg road' 'jp nagar'
 'BANNERGHATTA ROAD' 'MG ROAD' 'KANAKAPURA ROAD' 'HEBBAL' 'BELLARY ROAD'
 'electronic city' 'ELECTRONIC CITY' 'Bellary Road' 'Hennur Road'
 'rajajinagar' 'Kanakapura Road' 'INDIRANAGAR' 'hennur road'
 'kanakapura road' 'domlur' 'bannerghatta road' 'RAJAJINAGAR' 'hebbal'
 'Yelahanka' 'SARJAPUR ROAD' 'KORAMANGALA' 'Jp Nagar' 'JAYANAGAR']

In [ ]:
misspelling = {
    'Sarjapur Road':'SARJAPUR ROAD',
'Indiranagar':'INDIRANAGAR',
'Bannerghatta Road':'BANNERGHATTA ROAD',
'bellary road':'BELLARY ROAD',
'Koramangala':'KORAMANGALA',
'YELAHANKA':'YELAHANKA',
'whitefield':'WHITEFIELD',
'sarjapur road':'SARJAPUR ROAD',
'JP NAGAR':'JP NAGAR',
'Rajajinagar':'RAJAJINAGAR',
'koramangala':'KORAMANGALA',
'WHITEFIELD':'WHITEFIELD',
'indiranagar':'INDIRANAGAR',
'jayanagar':'JAYANAGAR',
'Whitefield':'WHITEFIELD',
'DOMLUR':'DOMLUR',
'yelahanka':'YELAHANKA',
'Mg Road':'MG ROAD',
'HENNUR ROAD':'HEBBAL ROAD',
'Jayanagar':'JAYANAGAR',
'Domlur':'DOMLUR',
'Electronic City':'ELECTRONIC CITY',
'Hebbal':'HEBBAL ROAD',
'mg road':'MG ROAD',
'jp nagar':'JP NAGAR',
'BANNERGHATTA ROAD':'BANNERGHATTA ROAD',
'MG ROAD':'MG ROAD',
'KANAKAPURA ROAD':'KANAKAPURA ROAD',
'HEBBAL':'HEBBAL ROAD',
'BELLARY ROAD':'BELLARY ROAD',
'electronic city':'ELECTRONIC CITY',
'ELECTRONIC CITY':'ELECTRONIC CITY',
'Bellary Road':'BELLARY ROAD',
'Hennur Road':'HEBBAL ROAD',
'rajajinagar':'RAJAJINAGAR',
'Kanakapura Road':'KANAKAPURA ROAD',
'INDIRANAGAR':'INDIRANAGAR',
'hennur road':'HEBBAL ROAD',
'kanakapura road':'KANAKAPURA ROAD',
'domlur':'DOMLUR',
'bannerghatta road':'BANNERGHATTA ROAD',
'RAJAJINAGAR':'RAJAJINAGAR',
'hebbal':'HEBBAL ROAD',
'Yelahanka':'YELAHANKA',
'SARJAPUR ROAD':'SARJAPUR ROAD',
'KORAMANGALA':'KORAMANGALA',
'Jp Nagar':'JP NAGAR',
'JAYANAGAR':'JAYANAGAR',

}
luxuryhouse_df['Area']= luxuryhouse_df['Area'].replace(misspelling)

In [ ]:
area_name = luxuryhouse_df['Area'].unique()
print(area_name)

['SARJAPUR ROAD' 'INDIRANAGAR' 'BANNERGHATTA ROAD' 'BELLARY ROAD'
 'KORAMANGALA' 'YELAHANKA' 'WHITEFIELD' 'JP NAGAR' 'RAJAJINAGAR'
 'JAYANAGAR' 'DOMLUR' 'MG ROAD' 'HEBBAL ROAD' 'ELECTRONIC CITY'
 'KANAKAPURA ROAD']

In [ ]:
luxuryhouse_df.head(5)

,Property_ID,Area,Project_Name,Developer_Name,Unit_Size_Sqft,Bedrooms,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,1,SARJAPUR ROAD,0,RMZ,4025.0,4,12.750846,Primary,NRI,3/31/2025,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,2,INDIRANAGAR,1,Puravankara,5760.0,3,16.292152,Primary,Other,6/30/2024,4.839024,5.000224,Under construction,NRI Desk,no,7.723898,106,NaN
2,3,BANNERGHATTA ROAD,2,Tata Housing,7707.0,4,10.517724,Primary,HNI,12/31/2023,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,4,BELLARY ROAD,3,Embassy,6192.0,3,9.396367,Primary,HNI,3/31/2024,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,5,KORAMANGALA,4,SNN Raj,7147.0,4,15.345392,Secondary,HNI,12/31/2024,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [ ]:
developer = luxuryhouse_df['Developer_Name'].unique()
print(developer)

['RMZ' 'Puravankara' 'Tata Housing' 'Embassy' 'SNN Raj' 'Brigade'
 'Prestige' 'Total Environment' 'Godrej' 'L&T Realty' 'Sobha']

In [ ]:
spell={
    'RMZ':'RMZ',
'Puravankara':'PURAVANKARA',
'Tata Housing':'TATA HOUSING',
'Embassy': 'EMBASSY',
'SNN Raj': 'SNN RAJ',
'Brigade':'BRIGADE',
'Prestige':'PRESTIGE',
'Total Environment':'TOTAL ENVIRONMENT',
'Godrej':'GODREJ',
'L&T Realty':'L&T REALTY',
'Sobha':'SOBHA'
}
luxuryhouse_df['Developer_Name']=luxuryhouse_df['Developer_Name'].replace(spell)

In [ ]:
transaction = luxuryhouse_df['Possession_Status'].unique()
print(transaction)

['Launch' 'Under construction' 'Ready to move']

In [ ]:
luxuryhouse_df.head(5)

,Property_ID,Area,Project_Name,Developer_Name,Unit_Size_Sqft,Bedrooms,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,1,SARJAPUR ROAD,0,RMZ,4025.0,4,12.750846,Primary,NRI,3/31/2025,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,2,INDIRANAGAR,1,PURAVANKARA,5760.0,3,16.292152,Primary,Other,6/30/2024,4.839024,5.000224,Under construction,NRI Desk,no,7.723898,106,NaN
2,3,BANNERGHATTA ROAD,2,TATA HOUSING,7707.0,4,10.517724,Primary,HNI,12/31/2023,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,4,BELLARY ROAD,3,EMBASSY,6192.0,3,9.396367,Primary,HNI,3/31/2024,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,5,KORAMANGALA,4,SNN RAJ,7147.0,4,15.345392,Secondary,HNI,12/31/2024,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [ ]:
luxuryhouse_df.to_csv('my_dataframe.csv', index=False)

In [ ]:
import pandas as pd
import math
luxuryhouse_df = pd.read_csv('/content/my_dataframe.csv')
luxuryhouse_df.head()

,Property_ID,Area,Project_Name,Developer_Name,Unit_Size_Sqft,Bedrooms,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,1,SARJAPUR ROAD,0,RMZ,4025.0,4,12.750846,Primary,NRI,3/31/2025,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,2,INDIRANAGAR,1,PURAVANKARA,5760.0,3,16.292152,Primary,Other,6/30/2024,4.839024,5.000224,Under construction,NRI Desk,no,7.723898,106,NaN
2,3,BANNERGHATTA ROAD,2,TATA HOUSING,7707.0,4,10.517724,Primary,HNI,12/31/2023,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,4,BELLARY ROAD,3,EMBASSY,6192.0,3,9.396367,Primary,HNI,3/31/2024,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,5,KORAMANGALA,4,SNN RAJ,7147.0,4,15.345392,Secondary,HNI,12/31/2024,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [ ]:
luxuryhouse_df['Purchase_Quarter']= pd.to_datetime(luxuryhouse_df['Purchase_Quarter'])
luxuryhouse_df['Purchase_Quarter'] = luxuryhouse_df['Purchase_Quarter'].dt.quarter
luxuryhouse_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86348 entries, 0 to 86347
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Property_ID           86348 non-null  int64
 1   Area                  86348 non-null  object
 2   Project_Name          86348 non-null  int64
 3   Developer_Name        86348 non-null  object
 4   Unit_Size_Sqft        86348 non-null  float64
 5   Bedrooms              86348 non-null  int64
 6   Ticket_Price_Cr       86348 non-null  float64
 7   Transaction_Type      86348 non-null  object
 8   Buyer_Type            86348 non-null  object
 9   Purchase_Quarter      86348 non-null  int32
 10  Connectivity_Score    86348 non-null  float64
 11  Amenity_Score         86348 non-null  float64
 12  Possession_Status     86348 non-null  object
 13  Sales_Channel         86348 non-null  object
 14  NRI_Buyer             86348 non-null  object
 15  Locality_Infra_Score  86348 non-null  float64
 16  Avg_Traffic_Time_Min  86348 non-null  int64
 17  Buyer_Comments        70648 non-null  object
dtypes: float64(5), int32(1), int64(4), object(8)
memory usage: 11.5+ MB

In [ ]:
luxuryhouse_df.head(5)

,Property_ID,Area,Project_Name,Developer_Name,Unit_Size_Sqft,Bedrooms,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,1,SARJAPUR ROAD,0,RMZ,4025.0,4,12.750846,Primary,NRI,1,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,2,INDIRANAGAR,1,PURAVANKARA,5760.0,3,16.292152,Primary,Other,2,4.839024,5.000224,Under construction,NRI Desk,no,7.723898,106,NaN
2,3,BANNERGHATTA ROAD,2,TATA HOUSING,7707.0,4,10.517724,Primary,HNI,4,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,4,BELLARY ROAD,3,EMBASSY,6192.0,3,9.396367,Primary,HNI,1,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,5,KORAMANGALA,4,SNN RAJ,7147.0,4,15.345392,Secondary,HNI,4,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

In [ ]:
luxuryhouse_df.to_csv('my_dataframe.csv', index=False)